### PR TITLE
Add teleport command

### PR DESCRIPTION
**Pull request by Bart-0110**
Is this alright if add this @licks92?

### CODE REVIEW

**Comment by licks92** [comment]
I'll tell you this evening, need to see what it does
Axel
Le 19 juin 2015 07:37, Bart-0110 <notifications@github.com> a écrit :Is this alright if add this @licks92?



You can view, comment on, or merge this pull request online at:
  https://github.com/licks92/WirelessRedstone/pull/97

Commit Summary

  Added teleport command


File Changes

  
    A
    Notes.txt
    (3)
  
  
    M
    src/main/java/net/licks92/WirelessRedstone/Permissions/WirelessPermissions.java
    (245)
  
  
    M
    src/main/java/net/licks92/WirelessRedstone/Strings/WirelessStrings.java
    (199)
  
  
    M
    src/main/java/net/licks92/WirelessRedstone/WirelessCommands.java
    (1936)
  
  
    M
    src/main/java/net/licks92/WirelessRedstone/WirelessRedstone.java
    (1)
  
  
    M
    src/main/resources/plugin.yml
    (10)
  


Patch Links:

  https://github.com/licks92/WirelessRedstone/pull/97.patch
  https://github.com/licks92/WirelessRedstone/pull/97.diff

**Comment by Bart-0110** [comment]
wr

Here's a screenshot how it works

**Comment by licks92** [comment]
Wow amazing what you did with the chat? Is that a new functionnality of bukkit? :D

**Comment by Bart-0110** [comment]
Yes. It is a new feature in Minecraft. You can send raw data and it has features to click and excecute something or hover over the text and show some enchantment information. Wiki: http://minecraft.gamepedia.com/Commands#tellraw

I also used a generator to create the json text which you can find here: http://minecraftjson.com/

**Comment by Bart-0110** [comment]
If you import this on the generator site you get the template: 

{"command":"/tellraw %%PLAYER %s","jobject":[{"text":"[","color":"dark_blue","clickEvent":{"action":"run_command","value":"[command]"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"%%TEXT","color":"gray"}]}}},{"text":"\\u27A4","color":"aqua","clickEvent":{"action":"run_command","value":"[command]"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"[tekst]","color":"gray"}]}}},{"text":"] ","color":"dark_blue","clickEvent":{"action":"run_command","value":"[command]"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"[tekst]","color":"gray"}]}}},{"text":"Name %%NAME, type: %%TYPE, world: %%WORLD, x: %%XCOORD, y: %%YCOORD, z: %%ZCOORD","color":"green","clickEvent":{"action":"run_command","value":"%%COMMAND"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"%%TEXT","color":"gray"}]}}}],"jtemplate":"tellraw"}

**Comment by licks92** [comment]
Well i gotta say well done. Maybe this could be linked to /wr info. When you execute /wri test r un exemple i already gives you location for all the receivers of the channel

**Comment by Bart-0110** [comment]
We could do that. I'll take a look

**Comment by licks92** [comment]
And iseriously need to fill the documentation about the plugin. I'm sure there's a lot of features that the users don't know

**Comment by Bart-0110** [comment]
Yes we need to do that. I already changed something in "The different kind of signs" but my English isn't the best.

**Pull request closed without merging**
